### ISSUE TITLE
AssociationRules returns error when support threshold is too high

### ISSUE THREAD

**Issue by abuchmueller** [TimToebrock/Project_Apriori#17] opened 2018-08-26 14:39 UTC
running ...

`result <- AssociationRules(Itemsets = Groceries, minsupport = 0.3, minconfidence = 0.4, maxConsequentLength = 10)`

...returns:

`Error in sparseMatrix(i = vec_names, j = vec_names, giveCsparse = FALSE,  : 
  all(dims >= dims.min) is not TRUE `

(This is the same behaviour as in issue #8)

**Comment by titoeb** [comment] 2018-08-26 14:44
Thanks for the issue but it is already fixed in the current commit " fixed error with too high support in frequent itemsets" this should already be fixed (i cannot reproduce the error in my version).

Can you check it again?

**Closed as completed** 2018-08-26 14:53 UTC
Labels: invalid
